"use client";
import AppShell from '../../components/AppShell';
import { useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { Panel } from '../../components/Cards';

export default function SettingsPage() {
  const [settings, setSettings] = useState<any>({});
  useEffect(()=>{ api('/api/settings').then(setSettings); }, []);
  const save = async() => { await api('/api/settings', { method:'POST', body: JSON.stringify(settings) }); alert('Settings saved locally'); };
  return <AppShell title="Settings" subtitle="Hardware, security, remote login, and gateway behavior"><div className="grid twoCol"><Panel title="Hardware and gateway"><div className="formGrid"><label><span>Device name</span><input className="field" value={settings.device_name || ''} onChange={e=>setSettings({...settings, device_name:e.target.value})} /></label><label><span>Management IP</span><input className="field" value={settings.management_ip || ''} onChange={e=>setSettings({...settings, management_ip:e.target.value})} /></label><label><span>WAN failover mode</span><select className="field" value={settings.failover_mode || ''} onChange={e=>setSettings({...settings, failover_mode:e.target.value})}><option>Auto</option><option>Priority</option><option>Load balance</option></select></label><label><span>Remote login</span><select className="field" value={String(settings.remote_login)} onChange={e=>setSettings({...settings, remote_login:e.target.value==='true'})}><option value="true">Enabled</option><option value="false">Disabled</option></select></label></div></Panel><Panel title="Security and gateway services"><div className="formGrid"><label><span>IDS default mode</span><select className="field" value={settings.ids_mode || ''} onChange={e=>setSettings({...settings, ids_mode:e.target.value})}><option>Detect only</option><option>Detect + block</option><option>Detect + quarantine</option></select></label><label><span>Geo default direction</span><select className="field" value={settings.geo_default_direction || ''} onChange={e=>setSettings({...settings, geo_default_direction:e.target.value})}><option>Outbound</option><option>Inbound</option><option>Both</option></select></label><label><span>VPN default provider</span><input className="field" value={settings.vpn_default_provider || ''} onChange={e=>setSettings({...settings, vpn_default_provider:e.target.value})} /></label><label><span>Topology auto-refresh</span><select className="field" value={settings.topology_refresh || ''} onChange={e=>setSettings({...settings, topology_refresh:e.target.value})}><option>15s</option><option>30s</option><option>60s</option></select></label></div></Panel></div><div className="topRow"><button className="primaryBtn" onClick={save}>Save all settings</button></div></AppShell>;
}
